// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _5eCombatTracker.Data.Helpers;

#nullable disable

namespace _5eCombatTracker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230426075255_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_5eCombatTracker.Data.Models.Monster", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("AC")
                        .HasColumnType("integer");

                    b.Property<string>("Alignment")
                        .HasColumnType("text");

                    b.Property<string>("CR")
                        .HasColumnType("text");

                    b.Property<int?>("HP")
                        .HasColumnType("integer");

                    b.Property<string>("Legendary")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Speed")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.Property<decimal?>("_Cha")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("_Con")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("_Dex")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("_Int")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("_Str")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("_Wis")
                        .HasColumnType("numeric");

                    b.HasKey("Name");

                    b.ToTable("monster", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
